#!/usr/bin/env python3
"""Assemble the static NextAvatar demo page.

Layout
------
The folder is self-contained: every asset the page loads lives under it and is
referenced with a path relative to it, so the folder can be served from any
sub-path (or pushed as its own repository).

    ref_images/                        reference images (anchor_XXXX.png)
    videos/comparison/qualified.csv    English prompts for the comparison cases
    videos/comparison/<model>/<id>.mp4
    videos/more_results/qualified.csv  English prompts for the long sequences
    videos/more_results/<name>.mp4
    videos/posters/...                 generated: first-frame JPEGs
    assets/figures/                    paper figures used by the text sections
    index.html                         generated: the two carousel sections

Sources
-------
Comparison clips for the six baselines are copied in from
``baselines_results/present_results/<model>/<id>.mp4``.  The ``nextavatar``
clips and every ``more_results`` clip are curated inputs: they are never copied
or overwritten.  The comparison case set is defined by the clips already
present in ``videos/comparison/nextavatar/``.

The two carousels are written into ``index.html`` between HTML comment markers,
so the prose stays hand-written while the clip lists stay generated.  Nothing
is fetched at run time: the markup is complete once this script finishes, and
the slides are switched by CSS alone.  That keeps the page working with scripts
disabled, which is how the Anonymous GitHub mirror serves it by default.

The CSS and JS URLs are rewritten with a content-hash query (see
``stamp_assets``) so that an edited asset is not served from the mirror's CDN
cache under its old name.

The script is idempotent: existing copies are skipped unless ``--force``.
Posters are extracted with ``ffmpeg``, which therefore has to be on PATH.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import re
import shutil
import subprocess
from pathlib import Path

SITE = Path(__file__).resolve().parent
PROJECT = SITE.parent
PRESENT = PROJECT / "baselines_results" / "present_results"

VIDEO_DIR = SITE / "videos" / "comparison"
MORE_DIR = SITE / "videos" / "more_results"
POSTER_DIR = SITE / "videos" / "posters"
REF_DIR = SITE / "ref_images"

INDEX = SITE / "index.html"
QUAL_BEGIN = "<!-- BEGIN:qualitative-carousel (generated by build_assets.py) -->"
QUAL_END = "<!-- END:qualitative-carousel -->"
MORE_BEGIN = "<!-- BEGIN:more-carousel (generated by build_assets.py) -->"
MORE_END = "<!-- END:more-carousel -->"

# Display order: proposed method first, then the six external systems.
MODELS: list[tuple[str, str, str]] = [
    ("nextavatar", "NextAvatar (Ours)", "ours"),
    ("longcat", "LongCat-Video-Avatar 1.5", "base"),
    ("flashtalk", "SoulX-FlashTalk", "base"),
    ("liveact", "SoulX-LiveAct", "base"),
    ("liveavatar", "Live Avatar", "base"),
    ("taomate", "TaoMate", "base"),
    ("aptavatar", "AptAvatar", "base"),
]


def read_prompts(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def split_prompt(prompt: str) -> tuple[str, str]:
    """Split a full prompt into its expression and action sentences."""
    expr = prompt.split("[Expression]")[-1].split("[Action]")[0].strip()
    act = (prompt.split("[Action]")[-1] if "[Action]" in prompt else "").strip()
    return expr, act


def copy(src: Path, dst: Path, force: bool) -> bool:
    if not src.exists():
        print(f"  [miss] {src}")
        return False
    if dst.exists() and not force:
        return True
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def ensure_poster(clip: Path, force: bool) -> Path:
    """Extract a clip's first frame as a small JPEG, used as its <video> poster.

    Every clip is a <video preload="none">, so without a poster the cell would
    stay black until the viewer presses play — and a viewer with scripts
    disabled has no other way to see what the clip starts from.
    """
    out = POSTER_DIR / clip.relative_to(SITE / "videos").with_suffix(".jpg")
    if out.exists() and not force:
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(clip),
            "-frames:v", "1", "-vf", "scale=288:-2", "-q:v", "4",
            str(out),
        ],
        check=True,
    )
    return out


def video_tag(src: str, path: Path, force: bool) -> str:
    """A <video> that loads nothing until asked, showing its first frame."""
    poster = ensure_poster(path, force).relative_to(SITE)
    return (
        f'<video src="{html.escape(src, quote=True)}"'
        f' poster="{html.escape(str(poster), quote=True)}"'
        ' muted playsinline preload="none" controls></video>'
    )


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def controls_html(name: str, index: int, count: int, play_title: str) -> str:
    """Arrows and counter as <label>s bound to the slide radios.

    Labels flip the radio directly, so paging needs no script at all.  The
    green replay button does need one and is revealed by ``html.js``.
    """
    prev_id = f"{name}-{(index - 2) % count + 1:02d}"
    next_id = f"{name}-{index % count + 1:02d}"
    return (
        '<div class="car-controls">'
        f'<label class="car-btn" for="{prev_id}" title="Previous (left arrow)">&#8249;</label>'
        f'<span class="car-counter">{index:02d} / {count:02d}</span>'
        f'<label class="car-btn" for="{next_id}" title="Next (right arrow)">&#8250;</label>'
        f'<button class="car-btn play" type="button" title="{esc(play_title)}">&#9654; Play</button>'
        "</div>"
    )


def carousel_html(name: str, slides: list[str]) -> str:
    """Wrap rendered slides in the radio + stage shell that switches them."""
    count = len(slides)
    radios = "".join(
        f'<input class="car-radio" type="radio" name="{name}" id="{name}-{i:02d}"'
        f'{" checked" if i == 1 else ""}>'
        for i in range(1, count + 1)
    )
    body = "".join(f'<div class="car-slide">{s}</div>' for s in slides)
    return (
        f'<div class="carousel" id="{name}-carousel">{radios}'
        f'<div class="car-stage">{body}</div></div>'
    )


def render_qualitative_slide(group: dict, index: int, count: int, force: bool) -> str:
    cells = [
        '<div class="clip ref">'
        f'<img src="{esc(group["ref"])}" alt="reference image" loading="lazy">'
        '<div class="clip-label">Reference</div></div>'
    ]
    for clip in group["clips"]:
        cells.append(
            f'<div class="clip{" ours" if clip["kind"] == "ours" else ""}">'
            f'{video_tag(clip["src"], clip["path"], force)}'
            f'<div class="clip-label">{esc(clip["label"])}</div></div>'
        )

    return (
        '<div class="car-fade">'
        '<div class="case-head">'
        '<div class="case-head-top">'
        f'<div class="case-idx">CASE {index:02d}</div>'
        f'{controls_html("qual", index, count, "Play all clips in this case from the start")}'
        "</div>"
        f'<div class="chip"><b>Action</b>{esc(group["action"])}</div>'
        "</div>"
        f'<div class="clip-grid">{"".join(cells)}</div>'
        "</div>"
    )


def render_more_slide(item: dict, index: int, count: int, force: bool) -> str:
    prompts = item["prompts"]
    items = "".join(
        '<div class="prompt-item"><div class="row">'
        f'<div class="pnum">{p["index"]:02d}</div>'
        f'<div class="sum"><div class="act"><span class="lab">Action</span>'
        f'{esc(p["action"])}</div></div>'
        "</div></div>"
        for p in prompts
    )

    return (
        '<div class="car-fade">'
        '<div class="sequence-head">'
        f'<div class="num">{index:02d}</div>'
        f'<div class="title">{len(prompts)} sequential expression&ndash;action instructions</div>'
        f'<div class="meta">{len(prompts)} prompts &middot; 24 fps</div>'
        f'{controls_html("more", index, count, "Play this sequence from the start")}'
        "</div>"
        '<div class="sequence-body">'
        '<div class="prompt-panel">'
        '<div class="prompt-panel-head"><span>Prompts</span>'
        f'<span class="spacer">01 &ndash; {len(prompts):02d}</span></div>'
        f'<div class="prompt-list">{items}</div>'
        "</div>"
        '<div class="media-col">'
        '<div class="seq-ref">'
        f'<img src="{esc(item["ref"])}" alt="reference image" loading="lazy">'
        '<div class="cap">Reference</div></div>'
        '<div class="seq-video">'
        f'{video_tag(item["src"], item["path"], force)}'
        '<div class="cap">Generated sequence</div></div>'
        "</div>"
        "</div>"
        "</div>"
    )


def build_qualitative(force: bool) -> str:
    by_id = {int(r["video_id"]): r for r in read_prompts(VIDEO_DIR / "qualified.csv")}

    groups = []
    for vid in qual_ids():
        row = by_id.get(vid)
        if row is None:
            print(f"  [miss] prompt for case {vid}")
            continue
        ref_name = Path(row["ref_image_path"]).name
        if not (REF_DIR / ref_name).exists():
            print(f"  [miss] ref_images/{ref_name}")
            continue

        clips = []
        for key, label, kind in MODELS:
            # Baseline clips are pulled from the results tree on demand; the
            # nextavatar clips are curated inputs and are never touched.
            if key != "nextavatar":
                copy(baseline_src(key, vid), VIDEO_DIR / key / f"{vid}.mp4", force)
            src = qual_clip(key, vid)
            if src is None:
                print(f"  [miss] case {vid} / {key}")
                continue
            clips.append({
                "model": key,
                "label": label,
                "kind": kind,
                "src": f"videos/comparison/{key}/{src.name}",
                "path": src,
            })

        prompt = row["prompt"]
        expr, act = split_prompt(prompt)
        groups.append({
            "id": vid,
            "ref": f"ref_images/{ref_name}",
            "prompt": prompt,
            "expression": expr,
            "action": act,
            "clips": clips,
        })
        print(f"  [qual] case {vid:02d}: {len(clips)} clips")

    count = len(groups)
    slides = [
        render_qualitative_slide(g, i, count, force)
        for i, g in enumerate(groups, 1)
    ]
    return carousel_html("qual", slides)


def build_more(force: bool) -> str:
    rows = read_prompts(MORE_DIR / "qualified.csv")

    # One sequence per file, in the order the file first appears in the CSV.
    order: list[str] = []
    per_file: dict[str, list[dict]] = {}
    for r in rows:
        if r["filename"] not in per_file:
            order.append(r["filename"])
        per_file.setdefault(r["filename"], []).append(r)

    videos = []
    for name in order:
        items = sorted(per_file[name], key=lambda r: int(r["within_video_id"]))
        path = MORE_DIR / name
        if not path.exists():
            print(f"  [miss] videos/more_results/{name}")
            continue
        ref_name = Path(items[0]["ref_image_path"]).name
        if not (REF_DIR / ref_name).exists():
            print(f"  [miss] ref_images/{ref_name}")
            continue

        prompts = []
        for r in items:
            expr, act = split_prompt(r["prompt"])
            prompts.append({
                "index": int(r["within_video_id"]),
                "expression": expr,
                "action": act,
                "full": r["prompt"],
            })

        videos.append({
            "id": int(items[0]["video_id"]),
            "ref": f"ref_images/{ref_name}",
            "src": f"videos/more_results/{name}",
            "path": path,
            "prompts": prompts,
        })
        print(f"  [more] {name}: {len(prompts)} prompts")

    count = len(videos)
    slides = [render_more_slide(v, i, count, force) for i, v in enumerate(videos, 1)]
    return carousel_html("more", slides)


def inject(begin: str, end: str, block: str) -> None:
    """Replace the marked region of index.html with generated markup."""
    text = INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"markers not found in {INDEX.name}: {begin}")
    INDEX.write_text(
        pattern.sub(lambda _: f"{begin}\n{block}\n{end}", text, count=1),
        encoding="utf-8",
    )


def qual_ids() -> list[int]:
    """The comparison case set is defined by the nextavatar clips in the repo."""
    ids = set()
    for p in (VIDEO_DIR / "nextavatar").glob("*_seed*.mp4"):
        try:
            ids.add(int(p.name.split("_", 1)[0]))
        except ValueError:
            continue
    return sorted(ids)


def baseline_src(model: str, video_id: int) -> Path:
    """On-disk path of one baseline clip in the results tree."""
    if model == "longcat":
        return PRESENT / "longcat" / "videos" / f"{video_id}.mp4"
    return PRESENT / model / f"{video_id:04d}.mp4"


def qual_clip(model: str, video_id: int) -> Path | None:
    """In-repo path of one comparison clip, or None when it is not there yet."""
    if model == "nextavatar":
        hits = sorted((VIDEO_DIR / model).glob(f"{video_id}_seed*.mp4"))
        return hits[0] if hits else None
    return VIDEO_DIR / model / f"{video_id}.mp4"


def stamp_assets() -> None:
    """Append a content hash to the CSS/JS URLs in index.html.

    The Anonymous GitHub mirror sits behind a CDN that keys its cache on the
    whole URL, so once ``style.css``/``main.js`` are cached an edited copy keeps
    being served under the same name -- the browser then runs the *old* script
    against the new markup.  Changing the query string changes the cache key.
    The mirror ignores the query when resolving the file, so the hash is purely
    a cache buster.
    """
    text = INDEX.read_text(encoding="utf-8")
    for rel in ("css/style.css", "js/main.js"):
        digest = hashlib.sha256((SITE / rel).read_bytes()).hexdigest()[:8]
        pattern = re.compile(
            r'((?:href|src)="' + re.escape(rel) + r')(?:\?v=[0-9a-f]+)?(")'
        )
        text, hits = pattern.subn(lambda m: f"{m.group(1)}?v={digest}{m.group(2)}", text)
        if not hits:
            raise SystemExit(f"asset not referenced in {INDEX.name}: {rel}")
    INDEX.write_text(text, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="overwrite existing clips/posters")
    ap.add_argument("--skip-qual", action="store_true")
    ap.add_argument("--skip-more", action="store_true")
    args = ap.parse_args()

    if not args.skip_qual:
        print("qualitative comparison:")
        inject(QUAL_BEGIN, QUAL_END, build_qualitative(args.force))
    if not args.skip_more:
        print("more results:")
        inject(MORE_BEGIN, MORE_END, build_more(args.force))
    stamp_assets()
    print(f"wrote {INDEX.relative_to(SITE)}")


if __name__ == "__main__":
    main()
